# Generated by Django 3.1.5 on 2021-01-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagina',
            options={'ordering': ['orden', 'titulo']},
        ),
        migrations.AddField(
            model_name='pagina',
            name='orden',
            field=models.SmallIntegerField(default=0),
        ),
    ]
