# Generated by Django 3.1.5 on 2021-01-14 01:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_auto_20210113_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
